# Generated by Django 3.2.19 on 2023-05-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_itemcategory_itemprice_itemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='min_level',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
