# Generated by Django 3.2.19 on 2023-05-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_remove_itemcategory_min_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='pharmacy_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='license',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importer',
            name='license',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='importer',
            name='sales_person',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='license_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
