# Generated by Django 3.2.19 on 2023-05-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Revenue', '0003_auto_20230507_0337'),
        ('setup', '0005_auto_20230506_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='Product_category',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
