# Generated by Django 3.2.19 on 2023-05-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20230507_0337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name_plural': 'Item categories'},
        ),
    ]
