# Generated by Django 3.2.19 on 2023-05-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_alter_itemcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemprice',
            name='Day_shift',
        ),
    ]
