# Generated by Django 3.2.19 on 2023-05-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='begininventory',
            name='min_level',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
