# Generated by Django 3.2.19 on 2023-05-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_begininventory_min_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begininventory',
            name='min_level',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
