# Generated by Django 3.2.19 on 2023-05-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_auto_20230507_0420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasedInventory',
        ),
    ]
