# Generated by Django 3.2.19 on 2023-05-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_purchasedinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedinventory',
            options={'verbose_name_plural': 'Purchased inventories'},
        ),
    ]
