# Generated by Django 3.2.19 on 2023-05-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableForSale',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('Item_category_id', models.CharField(max_length=250)),
                ('Item_type_id', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Inventoryunion',
                'managed': False,
            },
        ),
    ]
