# Generated by Django 3.2.19 on 2023-05-07 10:37

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_auto_20230506_0606'),
        ('Revenue', '0002_auto_20230506_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsale',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='newsale',
            name='product_type',
        ),
        migrations.AddField(
            model_name='newsale',
            name='item_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.itemcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsale',
            name='item_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='item_category', chained_model_field='item_category', default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.itemtype'),
            preserve_default=False,
        ),
    ]
