# Generated by Django 3.2.19 on 2023-05-07 10:39

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20230507_0337'),
        ('Revenue', '0003_auto_20230507_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsale',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='newsale',
            name='item_type',
        ),
        migrations.AddField(
            model_name='newsale',
            name='Item_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Item_category', chained_model_field='Item_category', default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.itemtype'),
            preserve_default=False,
        ),
    ]
