# Generated by Django 3.2.19 on 2023-05-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Revenue', '0005_auto_20230507_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsale',
            old_name='sale_single_price',
            new_name='Sale_single_price',
        ),
        migrations.RenameField(
            model_name='newsale',
            old_name='sale_total_price',
            new_name='Sale_total_price',
        ),
    ]
